url: http://otac0n.com
title: Technical Taco
tagline: 'I''m just some guy, you know?'
author_name: John Gietzen
author_email: otac0n@gietzen.us

permalink: /blog/:year/:month/:day/:title.html
future: false
markdown: rdiscount
exclude: run.cmd
